### ISSUE TITLE
Multi-Monitor setup

### ISSUE THREAD

**Issue by joseffilzmaier** [zzag/kwin-effects-appear1#1] opened 2018-05-12 10:57 UTC
Hello!
Thanks for those beautiful animations!

I have a small problem when using multiple monitors: (This report applies to all, {dis}appear{1,2,3} )
When using multiple monitors side by side the animation does not use the center of the current screen but rather the center of the combined screen space. This makes the animation shift a bit. Example Video: https://youtu.be/-pE5b7N3l_4
(See the little shift to the right there ;))
Thanks

**Comment by zzag** [comment] 2018-05-12 16:48
I can confirm this bug on a single monitor setup too. FWIW, Glide(from KWin) also has this bug. 

The cause of this bug is perspective projection, https://github.com/KDE/kwin/blob/master/plugins/scenes/opengl/scene_opengl.cpp#L1012

The fix would be to use only scale{X, Y} and translate{X, Y}, which doesn't make me so happy. How to fix Appear 2 and Disappear 2 I have no idea...

Thanks for spotting this nasty bug!

**Comment by zzag** [comment] 2018-05-12 18:14
3fef247ac2bd1af3c6ff2410d566a89612f9cfb4 should fix this bug. @joseffilzmaier could you please test that fix?

**Comment by zzag** [comment] 2018-05-12 20:04
Seems to be working on a dual monitor setup. Closing it.

**Closed as completed** 2018-05-12 20:04 UTC
Labels: bug

**Comment by zzag** [comment] 2018-05-12 21:15
I just took a look at libkwineffects API and it looks like it's possible to change projection matrix. I'll try to fix the perspective distortion at some time in the future.

**Comment by joseffilzmaier** [comment] 2018-05-13 11:55
Yes i can confirm that appear 3 and disappear 3 works now.
Thanks for the quick fix!
I absolutely love these subtle and smooth animations, i think animations like these should be the default in Plasma

**Comment by zzag** [comment] 2018-05-13 16:57
> Yes i can confirm that appear 3 and disappear 3 works now.

OK, that's good. :)

---

### Dev notes

Here's my thoughts how to fix Appear 2 and Disappear 2:

* Move window to the origin
* Rotate it
* Translate it
* Apply perspective projection
* Move window back to the "original" projected position

In theory, it should work.

**Comment by zzag** [comment] 2018-05-13 21:25
Appear 2 and Disappear 2 are now correctly working on multiple monitor setups.
Again, thanks for reporting this nasty bug. I would probably never notice it.

Thanks.
